version: "3"
services:
  web:
    image: welovelink/php74nginx
    container_name: ${APP_NAME}_web
    user: www-data
    #user: root
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./web-server.conf:/etc/nginx/conf.d/server.conf
  redis:
      image: redis:3.2.11
      container_name: ${APP_NAME}_redis
      restart: always
      privileged: true
      volumes:
          - ./local-redis.conf:/usr/local/etc/redis/redis.conf
          - ./init.sh:/usr/local/etc/redis/init.sh
      ports:
          - ${REDIS_PORT}:6379
      #command: ['redis-server', '/usr/local/etc/redis/redis.conf']
      command: sh -c "/usr/local/etc/redis/init.sh"
      logging:
          options:
              max-size: 5m
networks:
    default:
        external: false
        name: ${APP_NAME}_network
